apiVersion: 1

datasources:
  - name: Trino
    type: trino-datasource
    access: proxy
    url: http://trino:8080
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      catalog: memory
      schema: default

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
