[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    debug
    HTTP_Server  Off
    Parsers_File /fluent-bit/etc/parsers.conf
    # Parsers_File /fluent-bit/etc/custom_parsers.conf

# [INPUT]
#     Name              tail
#     # Path              /var/lib/docker/containers/*_simple-httpd-*/simple-httpd-json.log
#     Path              /var/lib/docker/containers/*/*.log
#     Exclude_Path      /var/lib/docker/containers/*fluent-git*/*.log
#     Parser            docker
#     Tag               httpd.*
#     Mem_Buf_Limit     5MB
#     Skip_Long_Lines   On
#     Docker_Mode   On
#     Path_Key      filepath

# [FILTER]
#     Name                kubernetes
#     Match               httpd.*
#     Kube_Tag_Prefix     httpd.var.log.containers.
#     Merge_Log           On
#     Keep_Log            Off

# [OUTPUT]
#     Name        loki
#     Match       httpd.*
#     Url         http://loki:3100
#     TenantID    ""
#     Labels      {job="httpd",container="simple-httpd"}
#     RemoveKeys  ["stream","docker","kubernetes","log"]

[OUTPUT]
    Name   stdout
    Match  *
    Format json_lines
