# https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/deployment/resource-providers/standalone/docker/#flink-with-docker-compose
# https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/catalogs/#catalog-store-configuration
# https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/deployment/config/#env-log-level

include:
  - compose-s3.yaml
  - compose-iceberg.yaml
  # docker compose up -d minio iceberg-rest
  # docker compose up -d jobmanager

services:
  jobmanager:
    image: flink:1.20.2
    ports:
      - 8081:8081
    command: jobmanager
    # volumes:
    #   - ./conf/catalog:/opt/flink/conf/catalog
    env_file:
      - .env.default

  taskmanager:
    image: flink:1.20.2
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./conf/catalog:/opt/flink/conf/catalog
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2     
        sql.catalog-store: file
        sql.catalog-store.file.directory: /opt/flink/conf/catalog
  
  sql-gateway:
    # docker compose up -d minio iceberg-rest jobmanager
    # docker compose up sql-gateway
    image: flink:1.20.2
    command: bin/sql-gateway.sh start-foreground
    depends_on:
      - jobmanager
    ports:
      - 8083:8083
    volumes:
      - ./conf/catalog:/opt/flink/conf/catalog
      - ./lib/iceberg-flink-runtime-1.20-1.9.2.jar:/opt/flink/lib/iceberg-flink-runtime-1.20-1.9.2.jar
      - ./lib/hadoop-common-3.3.1.jar:/opt/flink/lib/hadoop-common-3.3.1.jar
      - ./lib/hadoop-hdfs-3.3.1.jar:/opt/flink/lib/hadoop-hdfs-3.3.1.jar
      - ./lib/hadoop-hdfs-client-3.3.1.jar:/opt/flink/lib/hadoop-hdfs-client-3.3.1.jar
      - ./lib/flink-s3-fs-hadoop-1.20.1.jar:/opt/flink/lib/lib/flink-s3-fs-hadoop-1.20.1.jar
      # - ./lib:/opt/flink/plugins/iceberg
    environment:
      # https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql-gateway/overview/#starting-the-sql-gateway
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        sql-gateway.endpoint.rest.address: localhost
        table.catalog-store.kind: file
        table.catalog-store.file.path: file:///opt/flink/conf/catalog

  # sql-client:
  #   image: flink:1.20.2
  #   command: bin/sql-client.sh
  #   depends_on:
  #     - jobmanager
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       rest.address: jobmanager
