[SERVICE]
    Flush       1
    Daemon      Off
    Log_Level   debug
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name        systemd
    Tag         podman.*
    Strip_Underscores On
    Read_From_Tail On
    Lowercase On
    # Systemd_Filter _SYSTEMD_UNIT=podman.service
    # Systemd_Filter _SYSTEMD_USER_UNIT=podman.service
    # Systemd_Filter _COMM=common

[OUTPUT]
    Name        loki
    Match       *
    Host        loki
    Port        3100
    Labels      job=fluent-bit
    Label_Keys  $hostname,$container_name,$method,$path,$code
    Line_Format json

[FILTER]
    Name        grep
    Match       *
    Exclude     container_name fluent-bit
    # Regex       comm common

# [FILTER]
#     Name        rewrite_tag
#     Match       *
#     Rule        $container_name .*nginx.* podman.nginx flase

[FILTER]
    Name            parser
    Match           *
    Key_Name        message
    Parser          nginx
    Reserve_Data    true

[FILTER]
    Name        record_modifier
    Match       *

    Allowlist_Key    machine_id
    Allowlist_Key    hostname
    Allowlist_Key    container_name
    Allowlist_Key    container_id
    Allowlist_Key    message
    Allowlist_Key    source_realtime_timestamp

    # Name        modify
    # Remove      transport

