[SERVICE]
    Flush       1
    Daemon      Off
    Log_Level   debug

[INPUT]
    Name        tail
    Path        /var/log/nginx/*.log
    Tag         nginx.*
    Parser      nginx

# [FILTER]
#     Name        modify
#     Match       *
#     Remove      unwanted_field  # Replace 'unwanted_field' with the actual field name to delete

[OUTPUT]
    Name        stdout
    Match       *
