services:
  box-worker:
    image: alpine:latest
    command:
      - bash
      - -c
      - env | sort
    env_file:
      - default.env
      - production-worker.env
    # environment:
    #   COMPOSE_YAML: 1
