
include:
  - compose-loki.yaml

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    networks:
      - logging
  
  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    volumes:
      - ./fluent-bit:/fluent-bit/etc/conf
      # for input tail
      - ./logs/nginx:/var/log/nginx:ro
      # for input systemd (sudo usermod -aG systemd-journal $USER)
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    # command: -c /fluent-bit/etc/fluent-bit.conf
    command: -c /fluent-bit/etc/conf/nginx-tail-loki.conf
    networks:
      - logging

networks:
  logging:
