
include:
  - compose-loki.yaml

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - logging
  
  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    volumes:
      # - ./fluent-bit/nginx-tail-stdout.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit:/fluent-bit/etc/conf
      - ./logs/nginx:/var/log/nginx
    # command: -c /fluent-bit/etc/fluent-bit.conf
    command: -c /fluent-bit/etc/conf/nginx-tail-loki.conf
    networks:
      - logging

networks:
  logging:
